services:
  api_service:
    build:
      context: '.'
      dockerfile: Dockerfile
    container_name: api_service
    restart: always
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      api_db:
        condition: service_healthy
    volumes:
      - ./:/app
      - /app/node_modules
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/health']
      interval: 30s
      timeout: 10s
      retries: 3

  nats:
    image: nats:latest
    container_name: nats
    ports:
      - '4222:4222'
      - '8222:8222'
    command: "-js"

  api_db:
    image: postgres:15
    container_name: api_db
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: